license="MIT"
modLoader="javafml"
loaderVersion="47"
issueTrackerURL="https://github.com/Groupix05/DynamicTrees-Arts-and-Crafts/issues"

[[mods]]
modId="dtartsandcrafts"
version="${file.jarVersion}"
displayName="Dynamic Trees for Arts and Crafts"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-arts-and-crafts"
logoFile="logo.png"
credits=""
authors="Groupix05"
description='''
Adds Dynamic Trees compatibility for Arts and Crafts.
'''

[[dependencies.dtartsandcrafts]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtartsandcrafts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtartsandcrafts]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.3.6,)"
    ordering="AFTER"
    side="BOTH"
